name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Verify JAR file
      run: ls -la ./build/libs

#    - name: DockerHub Login
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_PASSWORD }}
#
#    - name: Docker Image Build
#      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }} .
#
#    - name: DockerHub Push
#      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}

    - name: Build Docker Image
      run: docker build -t my-app .

#    - name: Application Run
#      uses: appleboy/ssh-action@v0.1.6
#      with:
#        host: ${{ secrets.EC2_HOST }}
#        username: ${{ secrets.EC2_USERNAME }}
#        key: ${{ secrets.EC2_KEY }}
#
#        script: |
#          sudo docker stop my-app || true
#          sudo docker rm my-app || true
#          sudo docker rmi my-app || true
#          sudo docker run -p 8080:8080 \
#          --name my-app \
#          -e SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
#          -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
#          -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
#          -d my-app

    - name: Application Run
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        SSH_HOST: ${{ secrets.EC2_HOST }}
        SSH_USERNAME: ${{ secrets.EC2_USERNAME }}
      with:
        args: |
          sudo docker stop my-app || true
          sudo docker rm my-app || true
          sudo docker rmi my-app || true
          sudo docker run -p 8080:8080 \
          --name my-app \
          -e SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
          -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
          -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -d my-app

#          sudo docker kill ${{ secrets.PROJECT_NAME }}
#          sudo docker rm -f ${{ secrets.PROJECT_NAME }}
#          sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
#          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
#
#          sudo docker run -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
#          --name ${{ secrets.PROJECT_NAME }} \
#          -e SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
#          -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
#          -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
#          -d ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
